# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
from datetime import date
today = date.today().strftime("%d/%m/%Y")

# -- Project information -----------------------------------------------------

project = 'SPARTA'
copyright = '2020'
author = ''

# The full version, including alpha/beta/rc tags
release = '7 May 2020'

version = release + "  (build: {})".format(today)

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
# html_theme = 'sphinxdoc'
html_css_files = [
    'rtd_overrides.css',
]

#
# html_theme = 'alabaster'
# # For alabaster when it is very short
# html_sidebars = {
#     '**': [
#         'navigation.html',
#         # 'about.html'
#     ]
# }
# html_theme_options = {
#     # 'fixed_sidebar': True,
#     'body_text_align': 'justify',
#     'page_width': "auto"}

# html_theme_options = {'stickysidebar': True}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# OPTIONS FOR EPUB

epub_publisher = "J.F."
epub_use_index = True


# LATEX OPTIONS

latex_elements = {'preamble': r"""
\usepackage{enumitem}

\hypersetup{pdfborder={0 0 0}, pdftitle={SPARTA Manual},
  pdfsubject={DSMC},
  pdfpagemode={UseOutlines},
  pdfhighlight  =/P,
}
"""}
